<?php

/**
 * PluginInvoiceTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginInvoiceTable extends myBaseTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginInvoiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginInvoice');
    }
}